apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: myAKSCluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider
  forProvider:    
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        vnetSubnetIdRef:
          name: sub-crossplane
    dnsPrefix: aks
    identity:
      - type: SystemAssigned
    location: Central US
    resourceGroupNameRef:
      name: crossplane-rg
