apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: crossplane
  source:
    repoURL: https://github.com/nhatcao1105/crossplane-tutorial
    targetRevision: HEAD
    path: ./aws
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
      automated:
        prune: true    
      syncOptions:
      - CreateNamespace=true
      retry:
        limit: 1
        backoff:
          duration: 5s 
          factor: 2 
          maxDuration: 1m   